
    
    

const btn = document.querySelector(".btn.btn-hero")
// console.log(btn)
const color_text = document.querySelector(".color-text")

btn.addEventListener("click", function(){
    const getRandomNumber = () => Math.floor(Math.random() * colorList.length)
    const randomNumber = getRandomNumber();
    color_text.textContent = colorList[randomNumber]
    document.body.style.backgroundColor = colorList[randomNumber]
});


const colorList = [
    'silver',
    'gray',
    'maroon',
    'red',
    'purple',
    'fuchsia',
    'green',
    'lime',
    'olive',
    'yellow',
    'navy',
    'blue',
    'teal',
    'aqua',
    'aliceblue',
    'antiquewhite',
    'aqua',
    'aquamarine',
    'azure',
    'beige',
    'bisque',
    'blanchedalmond',
    'blueviolet',
    'brown',
    'burlywood',
    'cadetblue',
    'chartreuse',
    'chocolate',
    'coral',
    'cornflowerblue',
    'cornsilk',
    'crimson',
    'cyan',
    'darkblue',
    'darkcyan',
    'darkgoldenrod',
    'darkgray',
    'darkkhaki',
    'darmagenta',
    'darkolivergreen',
    'darkorange',
    'darkorchid',
    'darkred',
    'darksalmon',
    'darkturquoise',
    'deeppink',
    'darkslateblue',
    'deepskyblue',
    'dimgray',
    'dodgerblue',
    'firebrick',
    'floralwhite',
    'forestgreen',
    'fuchsia',
    'gainsboro',
    'ghostwhite',
    'goldenrod',
    'gold',
    'greenyellow',
    'honeydew',
    'indianred',
    'hotpink',
    'indigo',
    'ivory',
    'khaki',
    'lavender',
    'lavenderblush',
    'lawngreen',
    'lemonchiffon',
    'lightblue',
    'lightcoral',
    'lightcyan',
    'lightgoldenrodyellow',
    'ligthslategrey',
    'limegreen',
    'linen',
    'magenta',
    'maroon',
    'navy',
    'navajowhite',
    'moccasin',
    'mediumpurple',
    'mediumblue',
    'oldlace',
    'olivedrab',
    'orangered',
    'palegoldenrod',
    'palegreen',
    'plum',
    'powderblue',
    'rosybrown',
    'royalblue',
    'saddlebrown',
    'snow',
    'springgreen',
    'skyblue',
    'slateblue',
    'sienna',
    'seashell',
    'steelblue',
    'tan',
    'thistle',
    'tomato',
    'turquoise',
    'violet',
    'wheat',
    'white',
    'whitesmoke',
    'yellowgreen',
    ];